version: '3.8'

services:
  backend:
    build:
      context: ./visualizer-backend  # Set the build context to the visualizer-backend folder
      dockerfile: Dockerfile  # Specify the Dockerfile in the backend directory
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./visualizer-frontend  # Set the build context to the visualizer-frontend folder
      dockerfile: Dockerfile  # Specify the Dockerfile in the frontend directory
    ports:
      - "80:80"  # Expose port 80 for the frontend service
    networks:
      - app-network
    depends_on:
      - backend  # Ensure the backend starts first

networks:
  app-network:
    driver: bridge
